name: golangci-lint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.19]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Vendoring Go dependencies
        run: go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=5m
