name: golangci-lint
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    golangci:
        strategy:
            fail-fast: false
            matrix:
                go-version: [ '1.24' ]
        name: lint
        runs-on: ubuntu-latest
        steps:
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}
                    cache: true
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Linting
                uses: golangci/golangci-lint-action@v6
                with:
                    version: v1.64.5
                    args: --timeout=5m
