name: test
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    test:
        strategy:
            matrix:
                go-version: [ '1.20', '1.21', '1.22', '1.23', '1.24' ]
        name: test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}
            -   name: Print Go version
                run: go version
            -   name: Run tests
                run: go test -json ./... > test.json
            -   name: Annotate tests
                if: always()
                uses: guyarb/golang-test-annotations@v0.8.0
                with:
                    test-results: test.json
