name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23, 1.24]
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Print go version
        run: go version
      - name: Run tests
        run: go test -json ./... > test.json
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
